import { ImageSourcePropType } from "react-native";
import { AnimationName } from "../hooks/useSpriteAnimation";

// Preload all sprite frames
// This is more efficient than dynamic requires and ensures all frames are bundled
export const SPRITE_FRAMES: Record<AnimationName, ImageSourcePropType[]> = {
  Idle: [
    require("../assets/sprites/elf/Idle/0_Archer_Idle_000.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_001.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_002.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_003.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_004.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_005.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_006.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_007.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_008.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_009.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_010.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_011.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_012.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_013.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_014.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_015.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_016.png"),
    require("../assets/sprites/elf/Idle/0_Archer_Idle_017.png"),
  ],
  Walking: [
    require("../assets/sprites/elf/Walking/0_Archer_Walking_000.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_001.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_002.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_003.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_004.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_005.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_006.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_007.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_008.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_009.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_010.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_011.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_012.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_013.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_014.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_015.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_016.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_017.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_018.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_019.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_020.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_021.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_022.png"),
    require("../assets/sprites/elf/Walking/0_Archer_Walking_023.png"),
  ],
  Kicking: [
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_000.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_001.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_002.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_003.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_004.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_005.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_006.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_007.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_008.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_009.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_010.png"),
    require("../assets/sprites/elf/Kicking/0_Archer_Kicking_011.png"),
  ],
  Shooting: [
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_000.png"),
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_001.png"),
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_002.png"),
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_003.png"),
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_004.png"),
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_005.png"),
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_006.png"),
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_007.png"),
    require("../assets/sprites/elf/Shooting/0_Archer_Shooting_008.png"),
  ],
  Sliding: [
    require("../assets/sprites/elf/Sliding/0_Archer_Sliding_000.png"),
    require("../assets/sprites/elf/Sliding/0_Archer_Sliding_001.png"),
    require("../assets/sprites/elf/Sliding/0_Archer_Sliding_002.png"),
    require("../assets/sprites/elf/Sliding/0_Archer_Sliding_003.png"),
    require("../assets/sprites/elf/Sliding/0_Archer_Sliding_004.png"),
    require("../assets/sprites/elf/Sliding/0_Archer_Sliding_005.png"),
  ],
  Throwing: [
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_000.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_001.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_002.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_003.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_004.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_005.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_006.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_007.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_008.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_009.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_010.png"),
    require("../assets/sprites/elf/Throwing/0_Archer_Throwing_011.png"),
  ],
};